packages:
  - ./packages/**/*

catalog:
  '@arethetypeswrong/core': ^0.18.2
  '@chromatic-com/storybook': 4.1.1
  '@gaonengwww/eslint-config': ^1.0.5
  '@nuxt/content': ^3.8.0
  '@nuxtjs/content': ^0.3.0
  '@storybook/addon-a11y': 9.1.15
  '@storybook/addon-docs': 9.1.15
  '@storybook/addon-themes': ^9.1.15
  '@storybook/addon-vitest': 9.1.15
  '@storybook/vue3-vite': 9.1.15
  '@tailwindcss/vite': 4.1.16
  '@types/chroma-js': ^3.1.1
  '@types/node': ^24.6.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitest/browser-playwright': ^4.0.3
  '@vitest/coverage-v8': ^4.0.3
  '@vue/tsconfig': ^0.8.1
  chroma-js: ^3.1.2
  color2k: ^2.0.3
  deepmerge: ^4.3.1
  eslint: ^9.38.0
  eslint-plugin-storybook: 9.1.15
  flat: ^6.0.1
  motion-v: ^1.7.4
  playwright: ^1.56.1
  publint: ^0.3.15
  rimraf: ^6.0.1
  storybook: 9.1.15
  tailwind-merge: ^3.3.1
  tailwind-variants: ^3.1.1
  tailwindcss: 4.1.16
  tsdown: 0.15.9
  typescript: ~5.9.3
  unocss: 66.5.4
  unplugin-unused: ^0.5.4
  unplugin-vue: 7.0.3
  vite: ^7.1.7
  vitest: ^4.0.3
  vue: 3.5.22
  vue-tsc: 3.1.2

catalogMode: strict
