name: Build (Dry Run)

on:
  workflow_dispatch:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3.0.0
      - uses: actions/setup-node@v4
      - run: pnpm install
      - run: pnpm build:vue