name: Deploy site

on: workflow_dispatch

permissions:
  contents: write

jobs:
  Deploy:
    name: Deploy Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3.0.0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - run: pnpm i
      - run: pnpm build:site-vue
      - name: Depoly
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vitepress/dist

      