name: Test

on:
  pull_request:

jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3.0.0
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - run: pnpm install

      - name: Unit Test
        run: pnpm test:unit