name: Test

on:
  pull_request:
  workflow_dispatch:
    

jobs:
  unit-test:
    name: 🧪 Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3.0.0
      - name: Setup Nodejs
        uses: actions/setup-node@v4
      - run: pnpm install

      - name: Unit Test
        run: pnpm test:unit
  TypeTest:
    name: 🧪 Type test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3.0.0
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - run: pnpm install
      - name: Type Test
        run: pnpm test:type